furniture/furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('noksha.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

furniture/noksha/urls.py
from django.urls import path
from . import views
from .views import *
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'noksha'

urlpatterns = [
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('signup/',views.signUpUser,name="sign_up"),
    path('account/account_id=<str:pk>/',views.accountProfile,name="account_profile"),
    path('',views.home,name="home"),
    path('blogs/',views.blogs,name="blogs"),
    path('product_id=<str:pk>/',views.productView,name="product_view"),
    path('category/category_id=<str:pk>/',views.categoryView,name="category_view"),
    path('category/subcategory_id=<str:pk>/',views.subcategoryView,name="sub_category_view"),
    path('order/order_id=<str:pk>/',views.view_order,name="order_view"),
    path('blog/blog_id=<str:pk>/',views.blog,name="blog_view"),
    path('product/search=<str:searchtext>/',views.searchProduct,name="search_product"),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('update_item/',views.updateItem, name="update_item"),
    path('shop/dashboard/',shopDashboard.as_view(), name="shop_dashboard"),
    path('shop/view/order/<str:pk>/',views.updateOrder, name = 'update-order'),
    path('shop/products/',views.products, name = 'products'),
    path('shop/blogs/',views.shopBlogs, name = 'shop_blogs'),
    path('shop/product_id=<str:pk>/',views.shopProductView,name="shop_product_view"),
    path('shop/store/setting/',views.storeSettings,name="store_setting"),
    path('shop/store/banner/<str:pk>/',views.bannerSetting,name="banner_setting"),
    path('shop/store/collection/<str:pk>/',views.collectionSetting,name="collection_setting"),
    path('shop/store/shopnow/<str:pk>/',views.shopnowSetting,name="shopnow_setting"),
    path('shop/store/create/order/',views.createOrder,name="create_order"),
    path('shop/store/customer/<str:phone>/',views.fetchCustomer,name="fetch_customer"),
    path('shop/store/control/panel/',views.controlPanel,name="control_panel"),
    path('shop/store/customer/details/<str:pk>/',views.customerDetails,name="customer_details"),
]

furniture/noksha/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class ProductForm(ModelForm):
    name = forms.CharField(label='Product Name',widget=forms.TextInput(attrs={'placeholder': 'Product Name'}))
    price = forms.FloatField(label='Price',widget=forms.TextInput(attrs={'placeholder': 'Price'}))
    description = forms.CharField(max_length=2000,label='Description',widget=forms.Textarea(attrs={'placeholder': 'Description'}))
    product_code = forms.CharField(max_length=200,label='Product Code',widget=forms.TextInput(attrs={'placeholder': 'Product code'}))
    category = forms.ModelMultipleChoiceField(
            queryset=Category.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    color = forms.ModelMultipleChoiceField(
            queryset=Color.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    size = forms.ModelMultipleChoiceField(
            queryset=Size.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    
    class Meta:
        model = Product
        fields = '__all__'

furniture/noksha/views.py
from django.contrib.auth.hashers import check_password
from django.urls import reverse
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from .models import *
from .utils import *
from .forms import *
from .decorators import *
import math
import json
import datetime

# Create your views here.
def logoutUser(request):
    logout(request)
    return redirect('noksha:home')

def loginUser(request):
    #Navbar Section
    navbarCategoryObject =  IndivitualCategory.objects.get(category_for = 'nvcategory')
    navbarCategorys = navbarCategoryObject.categorys.all()

    #CartItem Section
    cookieData = cookieCart(request)
    cartItems = cookieData['cartItems']
    cartTotal = cookieData['cartTotal']
    order = cookieData['order']
    items = cookieData['items']
    total_items = len(items)
    delivery_charge_object = Delivery_charge.objects.get(w_delivery= 'Dhaka')
    delivery_charge = delivery_charge_object.fee
    price_total = 0

    #Login Section
    if request.method =='POST' and 'login_username' in request.POST:
        login_username = request.POST.get('login_username')
        password = request.POST.get('login_password')

        try:
            user_1 = User.objects.get(username = login_username)
            username = user_1.username
        except:
            customer_1 = Customer.objects.get(phone = login_username)
            user_1 =  customer_1.user
            username = user_1.username

        user = authenticate(request,username=username, password=password)
        login(request,user)
        if user_1.groups.all()[0].name == 'admin':
            return redirect('noksha:shop_dashboard')
        if user is not None:
            customer = Customer.objects.get(phone = login_username)
            shipping = ShippingAddress.objects.get(customer = customer)
            db_order, created = Order.objects.get_or_create(customer=customer, complete=False)
            db_order.cupon_code = order['cupon_code']
            db_order.cupon_amount = order['cupon_amount']
            db_order.address = shipping.address
            db_order.city = shipping.city
            db_order.state = shipping.state
            db_order.save()
            for item in items:
                product = Product.objects.get(id=item['product']['id'])
                quantity = item['quantity']
                rate = product.price
                total = float(product.price) * float(quantity)
                orderItem, created  = OrderItem.objects.get_or_create(
                    product=product,
                    order = db_order,
                    customer=customer
                )
                orderItem.quantity=item['quantity']
                orderItem.size = item['size']
                orderItem.color = item['color']
                orderItem.rate = rate,
                orderItem.total = total
                orderItem.save()
            messages.success(request,'Login Successfull!')
            return redirect('noksha:home')
        else:
            messages.error(request,'Login failed. Please try again!')
            return redirect('noksha:login')
    if total_items > 0:
        for item in items:
            product = Product.objects.get(id = item['product']['id'])
            item['sizes'] = product.size.all()
            item['colors'] = product.color.all()
            item['image'] = ProductImages.objects.filter(product = product)[:1]
            price_total += product.price
    
        total = float(price_total) + float(delivery_charge)

        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,
            'order':order,
            'items':items,
            'item.image':item['image'],
            'item.sizes':item['sizes'],
            'item.colors':item['colors'],
            'delivery_charge':delivery_charge,
            'total':total,

        }
    else:
        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,

        }
    return render(request,'accounts/login.html',context)

def signUpUser(request):
    #Navbar Section
    navbarCategoryObject =  IndivitualCategory.objects.get(category_for = 'nvcategory')
    navbarCategorys = navbarCategoryObject.categorys.all()

    #CartItem Section
    cookieData = cookieCart(request)
    cartItems = cookieData['cartItems']
    cartTotal = cookieData['cartTotal']
    order = cookieData['order']
    items = cookieData['items']
    total_items = len(items)
    delivery_charge_object = Delivery_charge.objects.get(w_delivery= 'Dhaka')
    delivery_charge = delivery_charge_object.fee
    price_total = 0

    #SignUp Section
    if request.method =='POST' and 'reg_name' in request.POST:
        name =  request.POST.get('reg_name')
        email =  request.POST.get('reg_email')
        phone =  request.POST.get('reg_phone')
        password1 =  request.POST.get('reg_password1')
        password2 =  request.POST.get('reg_password2')
        address =  request.POST.get('address')
        area =  request.POST.get('area')
        city =  request.POST.get('city')
        if User.objects.filter(email=email).first():
            messages.error(request, 'Email is taken.')
            return redirect('noksha:sign_up')
        elif Customer.objects.filter(phone = phone).first():
            messages.error(request, 'Phone is used on another account.')
            return redirect('noksha:sign_up')
        elif password1 != password2:
            messages.error(request, "Password didn't match!.")
            return redirect('noksha:sign_up')
        else:
            user = User.objects.create(first_name = name, email=email,username=phone)
            user.set_password(password1)
            user.save()
            customer = Customer.objects.create(
                    user = user,
                    phone = phone,
            )
            shipping =  ShippingAddress.objects.create(
                customer = customer,
                address = address,
                state = area,
                city = city
            )
            group = Group.objects.get(name = 'customer')
            user.groups.add(group)
            if user is not None:
                db_order, created = Order.objects.get_or_create(customer=customer, complete=False)
                db_order.address = shipping.address
                db_order.city = shipping.city
                db_order.state = shipping.state
                db_order.save()
                for item in items:
                    product = Product.objects.get(id=item['product']['id'])
                    quantity = item['quantity']
                    rate = product.price
                    total = float(product.price) * float(quantity)
                    orderItem, created  = OrderItem.objects.get_or_create(
                       product=product,
                        order = db_order,
                        customer=customer, 
                        )
                    orderItem.quantity=item['quantity']
                    orderItem.size = item['size']
                    orderItem.color = item['color']
                    orderItem.rate = rate,
                    orderItem.total = total
                    orderItem.save()
                login(request,user)
            messages.success(request,'Login Successfull!')
        return redirect('noksha:home')
    
    if total_items > 0:
        for item in items:
            product = Product.objects.get(id = item['product']['id'])
            item['sizes'] = product.size.all()
            item['colors'] = product.color.all()
            item['image'] = ProductImages.objects.filter(product = product)[:1]
            price_total += product.price
    
        total = float(price_total) + float(delivery_charge)

        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,
            'order':order,
            'items':items,
            'item.image':item['image'],
            'item.sizes':item['sizes'],
            'item.colors':item['colors'],
            'delivery_charge':delivery_charge,
            'total':total,

        }
    else:
        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,

        }
    return render(request,'accounts/registration.html',context)

@login_required(login_url='noksha:login')
def accountProfile(request,pk):
    user = request.user
    customer = request.user.customer
    user_orders = Order.objects.filter(customer=customer,complete = True).order_by('-date_created')

    #Status Section 
    total_orders = user_orders.count()
    delivered = user_orders.filter(status = 'Delivered').count()
    transit = user_orders.filter(status = 'In-Transit').count()
    confirmed = user_orders.filter(status = 'Admin Confirmed').count()
    pending = user_orders.filter(status = 'Customer Confirmed').count()
    
    status = {
        'total_orders':total_orders,
        'delivered':delivered,
        'transit':transit,
        'confirmed':confirmed, 
        'pending':pending,
    }

    #Wish List Section
    wish_products = []
    total_wish_products = 0
    if WishList.objects.filter(customer = customer).exists():
        wish_object = WishList.objects.get(customer = customer)
        for i in wish_object.products.all():

furniture/noksha/templates/store/components/dashboard.html
<script>
    function filterClick(status){
        $.each($("#table tbody tr"), function() {
            if(status.toLowerCase() == 'all')
                $(this).show();  
                else if($(this).text().toLowerCase().indexOf(status.toLowerCase()) === -1)
                $(this).hide();
            else
                $(this).show();                
         });
    }
</script>
<div class="row">
    <div class="col-sm-12"  style="overflow: auto;">
        <div class="user_dashboard">
            <div class="heading text-center">
                <h2>Dashboard</h2>
            </div> <br> <hr> <br>
            <div class="count_table">
                <style>
                    .row {
                    display: -ms-flexbox;
                    display: flex;
                    -ms-flex-wrap: wrap;
                    flex-wrap: wrap;
                    margin-right: -15px;
                    margin-left: -15px;
                }
                .col {
                    -ms-flex-preferred-size: 0;
                    flex-basis: 0;
                    -ms-flex-positive: 1;
                    flex-grow: 1;
                    max-width: 100%;
                    padding-right: 15px;
                    padding-left: 15px;
                }
                .card {
                    position: relative;
                    display: -ms-flexbox;
                    display: flex;
                    -ms-flex-direction: column;
                    flex-direction: column;
                    min-width: 0;
                    word-wrap: break-word;
                    background-color: #fff;
                    background-clip: border-box;
                    border: 1px solid rgba(0,0,0,.125);
                    border-radius: 0.25rem;
                    margin-bottom: 10px;
                }
                    .card-header {
                    padding: 0.75rem 1.25rem;
                    margin-bottom: 0;
                    background-color: rgba(0,0,0,.03);
                    border-bottom: 1px solid rgba(0,0,0,.125);
                }
                .card-body {
                    -ms-flex: 1 1 auto;
                    flex: 1 1 auto;
                    min-height: 1px;
                    padding: 1.25rem;
                }
                .text-white h5{
                    font-size: 12px;
                }
                .text-white h5,.text-white h3{
                    color: black !important;
                }
                </style>
                <div class="row">
                    <div class="col">
                        <div class="col-md">
                            <div class="card text-center text-white md-3" id="total-orders">
                                <a onclick="filterClick('all')" style="color: white !important; text-decoration:none;">
                                    <div class="card-header">
                                        <h5 class="card-title">Total Orders</h5>
                                    </div>
                                    <div class="card-body">
                                        <h3 class="card-title">{{status.total_orders}}</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="col-md">
                            <div class="card text-center text-white md-3" id="orders-delivered">
                                <a onclick="filterClick('delivered')" style="color: white !important; text-decoration:none;">
                                    <div class="card-header">
                                        <h5 class="card-title">Delivered</h5>
                                    </div>
                                    <div class="card-body">
                                        <h3 class="card-title">{{status.delivered}}</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="col-md">
                            <div class="card text-center text-white md-3" id="orders-transit">
                                <a onclick="filterClick('In Transit')" style="color: white !important; text-decoration:none;">
                                    <div class="card-header">
                                        <h5 class="card-title">In Transit</h5>
                                    </div>
                                    <div class="card-body">
                                        <h3 class="card-title">{{status.transit}}</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col">
                        <div class="col-md">
                            <div class="card text-center text-white md-3" id="orders-confirmed">
                                <a onclick="filterClick('Confirmed')" style="color: white !important; text-decoration:none;">
                                    <div class="card-header">
                                        <h5 class="card-title">Confirmed</h5>
                                    </div>
                                    <div class="card-body">
                                        <h3 class="card-title">{{status.confirmed}}</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="col-md">
                            <div class="card text-center text-white md-3" id="orders-pending">
                                <a onclick="filterClick('Pending')" style="color: white !important; text-decoration:none;">
                                    <div class="card-header">
                                        <h5 class="card-title">Pending</h5>
                                    </div>
                                    <div class="card-body">
                                        <h3 class="card-title">{{status.pending}}</h3>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><br> <hr> <br>
            <div class="user_orders">
                
<div class="row">
    <div class="col-sm-12" style="
    overflow: hidden;
">
        
        <div class="table-responsive">
            <table class="table table-bordered" id="table">
                <thead>
                    <tr> 
                        <td class="text-center">Memo No.</td>
                        <td class="text-left">Status</td>
                        <td class="text-left">Method</td>
                        <td class="text-left">Date</td>
                        <td class="text-left">Total</td>
                        <td class="text-left">Paid</td>
                        <td class="text-left">Due</td>
                        <td class="text-center">View</td>
                    </tr>
                </thead>
                <tbody>
                    {% for order in filterOrders %}
                    <tr>
                        <td class="text-center">{{order.id}}</td>
                        <td class="text-left">
                            {% if order.status == 'Customer Confirmed' %}
                            Pending
                            {% elif order.status == 'Admin Confirmed' %}
                            Confirmed
                            {% elif order.status == 'In-Transit' %}
                            In Transit
                            {% elif order.status == 'Delivered' %}
                            Delivered
                            {% else %}
                            Cancel
                            {% endif %}
                        </td>
                        <td class="text-left">
                            {% if order.method == 'cod' %}
                            Cash on delivery
                            {% else %}
                            {{order.method}}
                            {% endif %}
                        </td>
                        <td class="text-left">{{order.date_created|date:'M d, Y'}}</td>
                        <td class="text-left">{{order.total|floatformat:0}}&#2547;</td>
                        <td class="text-left">{{order.advance|floatformat:0}}&#2547;</td>
                        <td class="text-left">{{order.due|floatformat:0}}&#2547;</td>
                        <td class="text-center">
                            <a href="{% url 'noksha:order_view' order.id %}" style="
                            background: #4cb4c7;
                            color: #fff;
                            padding: 2px 4px;
                            border: 1px solid #ddd;
                            border-radius: 7px;">
                                <i class="fa fa-eye" aria-hidden="true" style="font-size: 15px;"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}     
                </tbody>
            </table>
        </div>
    </div>
</div>
            </div>
        </div>
    </div>
</div>

furniture/noksha/templates/store/components/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fa fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fa fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fa fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fa fa-linkedin"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fa fa-diamond me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fa fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fa fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fa fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fa fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2022 Copyright:
      <a class="text-reset fw-bold" href="">Noksha.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

furniture/noksha/templates/store/components/header.html
{% load static %}
<style>
    .logo-img{
        max-width: 100px;
    }
    .navbar {
        position: fixed;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        -ms-flex-align: center;
        align-items: center;
        -ms-flex-pack: justify;
        justify-content: space-between;
        padding: 0.5rem 1rem;
        z-index: 99;
        width: 100%;
        background-color: transparent;
    }
    .bg-light {
        background-color: #f8f9fad9!important;
    }
    .navbar .btn-primary{
        background-color: transparent;
        color: black;
        border: none;
    }
    .navbar .btn-primary .badge-light{
        background-color: #43f1ffc2;
        border-radius: 50%;
        margin-left: -7px;
        padding: 3px 7px;
        position: absolute;
        margin-top: 11px;
        font-size: 15px;
    }
</style>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'noksha:home' %}">
            <img class="logo-img" src="{% static 'images/logo.png' %}" alt="NOKSHA">
        </a>
    
        <a href="{% url 'noksha:cart' %}" type="button" class="btn btn-primary" >
            <i class="fa fa-shopping-cart" aria-hidden="true" style="font-size: 25px;"></i> <span class="badge badge-light">{{cartItems}}</span>
            <span class="sr-only">unread messages</span>
        </a>
        <button class="navbar-toggler" type="button" style="font-size: 0.75rem; padding: 2px 5px; justify-self: flex-end;" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <di class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'noksha:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% for i in nvCategorys %}
            <li>
                <a class="nav-link" href="{% url 'noksha:category_view' i.id %}">{{i.name}}</a>
            </li>
            {% endfor %}
            {% if request.user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'noksha:account_profile' request.user.id %}">Account</a>
            </li>
            {% else %}
            <li class="nav-item">
            <a class="nav-link" href="#">Login</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Signup</a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        </div>
    </nav>
</header>