furniture/furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('noksha.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

furniture/noksha/urls.py
from django.urls import path
from . import views
from .views import *
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'noksha'

urlpatterns = [
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('signup/',views.signUpUser,name="sign_up"),
    path('account/account_id=<str:pk>/',views.accountProfile,name="account_profile"),
    path('',views.home,name="home"),
    path('blogs/',views.blogs,name="blogs"),
    path('product_id=<str:pk>/',views.productView,name="product_view"),
    path('category/category_id=<str:pk>/',views.categoryView,name="category_view"),
    path('category/subcategory_id=<str:pk>/',views.subcategoryView,name="sub_category_view"),
    path('order/order_id=<str:pk>/',views.view_order,name="order_view"),
    path('blog/blog_id=<str:pk>/',views.blog,name="blog_view"),
    path('product/search=<str:searchtext>/',views.searchProduct,name="search_product"),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('update_item/',views.updateItem, name="update_item"),
    path('shop/dashboard/',shopDashboard.as_view(), name="shop_dashboard"),
    path('shop/view/order/<str:pk>/',views.updateOrder, name = 'update-order'),
    path('shop/products/',views.products, name = 'products'),
    path('shop/blogs/',views.shopBlogs, name = 'shop_blogs'),
    path('shop/product_id=<str:pk>/',views.shopProductView,name="shop_product_view"),
    path('shop/store/setting/',views.storeSettings,name="store_setting"),
    path('shop/store/banner/<str:pk>/',views.bannerSetting,name="banner_setting"),
    path('shop/store/collection/<str:pk>/',views.collectionSetting,name="collection_setting"),
    path('shop/store/shopnow/<str:pk>/',views.shopnowSetting,name="shopnow_setting"),
    path('shop/store/create/order/',views.createOrder,name="create_order"),
    path('shop/store/customer/<str:phone>/',views.fetchCustomer,name="fetch_customer"),
    path('shop/store/control/panel/',views.controlPanel,name="control_panel"),
    path('shop/store/customer/details/<str:pk>/',views.customerDetails,name="customer_details"),
]

furniture/noksha/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class ProductForm(ModelForm):
    name = forms.CharField(label='Product Name',widget=forms.TextInput(attrs={'placeholder': 'Product Name'}))
    price = forms.FloatField(label='Price',widget=forms.TextInput(attrs={'placeholder': 'Price'}))
    description = forms.CharField(max_length=2000,label='Description',widget=forms.Textarea(attrs={'placeholder': 'Description'}))
    product_code = forms.CharField(max_length=200,label='Product Code',widget=forms.TextInput(attrs={'placeholder': 'Product code'}))
    category = forms.ModelMultipleChoiceField(
            queryset=Category.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    color = forms.ModelMultipleChoiceField(
            queryset=Color.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    size = forms.ModelMultipleChoiceField(
            queryset=Size.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    
    class Meta:
        model = Product
        fields = '__all__'

furniture/noksha/views.py
from django.contrib.auth.hashers import check_password
from django.urls import reverse
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from .models import *
from .utils import *
from .forms import *
from .decorators import *
import math
import json
import datetime

# Create your views here.
def logoutUser(request):
    logout(request)
    return redirect('noksha:home')

def loginUser(request):
    #Navbar Section
    navbarCategoryObject =  IndivitualCategory.objects.get(category_for = 'nvcategory')
    navbarCategorys = navbarCategoryObject.categorys.all()

    #CartItem Section
    cookieData = cookieCart(request)
    cartItems = cookieData['cartItems']
    cartTotal = cookieData['cartTotal']
    order = cookieData['order']
    items = cookieData['items']
    total_items = len(items)
    delivery_charge_object = Delivery_charge.objects.get(w_delivery= 'Dhaka')
    delivery_charge = delivery_charge_object.fee
    price_total = 0

    #Login Section
    if request.method =='POST' and 'login_username' in request.POST:
        login_username = request.POST.get('login_username')
        password = request.POST.get('login_password')

        try:
            user_1 = User.objects.get(username = login_username)
            username = user_1.username
        except:
            customer_1 = Customer.objects.get(phone = login_username)
            user_1 =  customer_1.user
            username = user_1.username

        user = authenticate(request,username=username, password=password)
        login(request,user)
        if user_1.groups.all()[0].name == 'admin':
            return redirect('noksha:shop_dashboard')
        if user is not None:
            customer = Customer.objects.get(phone = login_username)
            shipping = ShippingAddress.objects.get(customer = customer)
            db_order, created = Order.objects.get_or_create(customer=customer, complete=False)
            db_order.cupon_code = order['cupon_code']
            db_order.cupon_amount = order['cupon_amount']
            db_order.address = shipping.address
            db_order.city = shipping.city
            db_order.state = shipping.state
            db_order.save()
            for item in items:
                product = Product.objects.get(id=item['product']['id'])
                quantity = item['quantity']
                rate = product.price
                total = float(product.price) * float(quantity)
                orderItem, created  = OrderItem.objects.get_or_create(
                    product=product,
                    order = db_order,
                    customer=customer
                )
                orderItem.quantity=item['quantity']
                orderItem.size = item['size']
                orderItem.color = item['color']
                orderItem.rate = rate,
                orderItem.total = total
                orderItem.save()
            messages.success(request,'Login Successfull!')
            return redirect('noksha:home')
        else:
            messages.error(request,'Login failed. Please try again!')
            return redirect('noksha:login')
    if total_items > 0:
        for item in items:
            product = Product.objects.get(id = item['product']['id'])
            item['sizes'] = product.size.all()
            item['colors'] = product.color.all()
            item['image'] = ProductImages.objects.filter(product = product)[:1]
            price_total += product.price
    
        total = float(price_total) + float(delivery_charge)

        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,
            'order':order,
            'items':items,
            'item.image':item['image'],
            'item.sizes':item['sizes'],
            'item.colors':item['colors'],
            'delivery_charge':delivery_charge,
            'total':total,

        }
    else:
        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,

        }
    return render(request,'accounts/login.html',context)

def signUpUser(request):
    #Navbar Section
    navbarCategoryObject =  IndivitualCategory.objects.get(category_for = 'nvcategory')
    navbarCategorys = navbarCategoryObject.categorys.all()

    #CartItem Section
    cookieData = cookieCart(request)
    cartItems = cookieData['cartItems']
    cartTotal = cookieData['cartTotal']
    order = cookieData['order']
    items = cookieData['items']
    total_items = len(items)
    delivery_charge_object = Delivery_charge.objects.get(w_delivery= 'Dhaka')
    delivery_charge = delivery_charge_object.fee
    price_total = 0

    #SignUp Section
    if request.method =='POST' and 'reg_name' in request.POST:
        name =  request.POST.get('reg_name')
        email =  request.POST.get('reg_email')
        phone =  request.POST.get('reg_phone')
        password1 =  request.POST.get('reg_password1')
        password2 =  request.POST.get('reg_password2')
        address =  request.POST.get('address')
        area =  request.POST.get('area')
        city =  request.POST.get('city')
        if User.objects.filter(email=email).first():
            messages.error(request, 'Email is taken.')
            return redirect('noksha:sign_up')
        elif Customer.objects.filter(phone = phone).first():
            messages.error(request, 'Phone is used on another account.')
            return redirect('noksha:sign_up')
        elif password1 != password2:
            messages.error(request, "Password didn't match!.")
            return redirect('noksha:sign_up')
        else:
            user = User.objects.create(first_name = name, email=email,username=phone)
            user.set_password(password1)
            user.save()
            customer = Customer.objects.create(
                    user = user,
                    phone = phone,
            )
            shipping =  ShippingAddress.objects.create(
                customer = customer,
                address = address,
                state = area,
                city = city
            )
            group = Group.objects.get(name = 'customer')
            user.groups.add(group)
            if user is not None:
                db_order, created = Order.objects.get_or_create(customer=customer, complete=False)
                db_order.address = shipping.address
                db_order.city = shipping.city
                db_order.state = shipping.state
                db_order.save()
                for item in items:
                    product = Product.objects.get(id=item['product']['id'])
                    quantity = item['quantity']
                    rate = product.price
                    total = float(product.price) * float(quantity)
                    orderItem, created  = OrderItem.objects.get_or_create(
                       product=product,
                        order = db_order,
                        customer=customer, 
                        )
                    orderItem.quantity=item['quantity']
                    orderItem.size = item['size']
                    orderItem.color = item['color']
                    orderItem.rate = rate,
                    orderItem.total = total
                    orderItem.save()
                login(request,user)
            messages.success(request,'Login Successfull!')
        return redirect('noksha:home')
    
    if total_items > 0:
        for item in items:
            product = Product.objects.get(id = item['product']['id'])
            item['sizes'] = product.size.all()
            item['colors'] = product.color.all()
            item['image'] = ProductImages.objects.filter(product = product)[:1]
            price_total += product.price
    
        total = float(price_total) + float(delivery_charge)

        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,
            'order':order,
            'items':items,
            'item.image':item['image'],
            'item.sizes':item['sizes'],
            'item.colors':item['colors'],
            'delivery_charge':delivery_charge,
            'total':total,

        }
    else:
        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,

        }
    return render(request,'accounts/registration.html',context)

@login_required(login_url='noksha:login')
def accountProfile(request,pk):
    user = request.user
    customer = request.user.customer
    user_orders = Order.objects.filter(customer=customer,complete = True).order_by('-date_created')

    #Status Section 
    total_orders = user_orders.count()
    delivered = user_orders.filter(status = 'Delivered').count()
    transit = user_orders.filter(status = 'In-Transit').count()
    confirmed = user_orders.filter(status = 'Admin Confirmed').count()
    pending = user_orders.filter(status = 'Customer Confirmed').count()
    
    status = {
        'total_orders':total_orders,
        'delivered':delivered,
        'transit':transit,
        'confirmed':confirmed, 
        'pending':pending,
    }

    #Wish List Section
    wish_products = []
    total_wish_products = 0
    if WishList.objects.filter(customer = customer).exists():
        wish_object = WishList.objects.get(customer = customer)
        for i in wish_object.products.all():

furniture/noksha/templates/shop/main.html
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>H A S H T A G</title>

    {% include 'shop/components/links.html' %}
    

    <style>
        
        #preloader {
            background-color: #ffffff73;
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            z-index: 9999;
        }

        #status {
            background-image: url('/static/images/AjaxLoader.gif');
            background-repeat: no-repeat;
            width: 100px;
            height: 100px;
            position: absolute;
            left: 50%;
            top: 50%;
            margin-top: -35px;
            margin-left: -35px;
        }
        #orders-cancel {
            background-color: #ee3333;
        }
        #orders-return {
            background-color: #eeb133;
        }
        
    </style>
    <script>
        /* =========================================
                Preloader
        ============================================ */
        $(window).on('load', function () { // makes sure that whole site is loaded
            $('#status').fadeOut();
            $('#preloader').delay(350).fadeOut('slow');
        });

    </script>
</head>
{% if messages %}
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}
{% endif %}

<body>
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>
    {% load static %}

<style>
    #logo a img {
        width: 85px;
    }
    #logo{
        margin-top: -15px;
    }
    .has-scroll .table tbody tr td a img{
        max-width: 55px;
    }
    .text-left span{
        font-size: 10px;
    }
    .breadcrumbs {
        display: none;
    }
</style>
<header>
	<div class="container-fix">
        <div class="logo-container pull-left">
            <div id="logo">
                <a href="{% url 'noksha:shop_dashboard' %}">
                    <img src="{% static 'images/logo.png' %}" title="H A S H T A G" alt="H A S H T A G" class="img-responsive" />
                </a>
            </div>
        </div>
        	
	    <div class="block-right pull-right">
            <div class="search-containers pull-right" style="margin-right: 12px;">
                <div class="search-container">
                    <a href="{% url 'noksha:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                </div>
            </div>	
            <div class="search-containers pull-right" style="margin-right: 12px;">
                <div class="search-container">
                    <a href="http://127.0.0.1:8000/admin"><i class="fa fa-indent" aria-hidden="true"></i></a>
                </div>
            </div>	
            <div class="search-containers pull-right" style="margin-right: 12px;">
                <div class="search-container">
                    <a href="{% url 'noksha:home' %}"><i class="fa fa-globe" aria-hidden="true"></i></a>
                </div>
            </div>			
        </div>	
	    <div class="container">
		    <div class="main-menu">
				<div class="hozmenu-container">
	                <div class="ma-nav-mobile-container">
		                <div class="hozmenu">
			                <div class="navbar">
				                <div id="navbar-inner" class="navbar-inner navbar-inactive">
						            <div class="menu-mobile">
							            <a class="btn btn-navbar navbar-toggle">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </a>
                                        <span class="brand navbar-brand">Menu</span>
                                    </div>
				
					                <ul id="ma-mobilemenu" class="mobilemenu nav-collapse collapse">
                                        <li>
                                            <a href="{% url 'noksha:shop_dashboard' %}">Dashboard</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'noksha:products' %}">Products</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'noksha:shop_blogs' %}">Blogs</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'noksha:store_setting' %}">Store Settings</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'noksha:create_order' %}">Create Order</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'noksha:control_panel' %}">Control Panel</a>
                                        </li>
                                    </ul> 
				
			                    </div>
			                </div>
		                </div>
	                </div>
                    <div class="nav-container visible-lg visible-md">		
		                <div id="pt_custommenu" class="pt_custommenu">
				            <div id="pt_menu_home" class="pt_menu">
                                <div class="parentMenu">
                                    <a href="{% url 'noksha:shop_dashboard' %}">
                                        <span>Dashboard</span>
                                    </a>
                                </div>
                            </div>
				            <div id="pt_menu_home" class="pt_menu">
                                <div class="parentMenu">
                                    <a href="{% url 'noksha:products' %}">
                                        <span>Products</span>
                                    </a>
                                </div>
                            </div>
				            <div id="pt_menu_home" class="pt_menu">
                                <div class="parentMenu">
                                    <a href="{% url 'noksha:shop_blogs' %}">
                                        <span>Blogs</span>
                                    </a>
                                </div>
                            </div>
				            <div id="pt_menu_home" class="pt_menu">
                                <div class="parentMenu">
                                    <a href="{% url 'noksha:store_setting' %}">
                                        <span>Store Settings</span>
                                    </a>
                                </div>
                            </div>
				            <div id="pt_menu_home" class="pt_menu">
                                <div class="parentMenu">
                                    <a href="{% url 'noksha:create_order' %}">
                                        <span>Create Order</span>
                                    </a>
                                </div>
                            </div>
				            <div id="pt_menu_home" class="pt_menu">
                                <div class="parentMenu">
                                    <a href="{% url 'noksha:control_panel' %}">
                                        <span>Control Panel</span>
                                    </a>
                                </div>
                            </div>
		                </div>
	                </div>
                </div>
                <div id="sticky-menu" data-sticky="1"></div>
			</div>
	    </div>
	</div>
</header>
        {% block content %}
        {% endblock %}
    </body>
</html>