furniture/furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('noksha.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

furniture/noksha/urls.py
from django.urls import path
from . import views
from .views import *
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'noksha'

urlpatterns = [
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('signup/',views.signUpUser,name="sign_up"),
    path('account/account_id=<str:pk>/',views.accountProfile,name="account_profile"),
    path('',views.home,name="home"),
    path('blogs/',views.blogs,name="blogs"),
    path('product_id=<str:pk>/',views.productView,name="product_view"),
    path('category/category_id=<str:pk>/',views.categoryView,name="category_view"),
    path('category/subcategory_id=<str:pk>/',views.subcategoryView,name="sub_category_view"),
    path('order/order_id=<str:pk>/',views.view_order,name="order_view"),
    path('blog/blog_id=<str:pk>/',views.blog,name="blog_view"),
    path('product/search=<str:searchtext>/',views.searchProduct,name="search_product"),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('update_item/',views.updateItem, name="update_item"),
    path('shop/dashboard/',shopDashboard.as_view(), name="shop_dashboard"),
    path('shop/view/order/<str:pk>/',views.updateOrder, name = 'update-order'),
    path('shop/products/',views.products, name = 'products'),
    path('shop/blogs/',views.shopBlogs, name = 'shop_blogs'),
    path('shop/product_id=<str:pk>/',views.shopProductView,name="shop_product_view"),
    path('shop/store/setting/',views.storeSettings,name="store_setting"),
    path('shop/store/banner/<str:pk>/',views.bannerSetting,name="banner_setting"),
    path('shop/store/collection/<str:pk>/',views.collectionSetting,name="collection_setting"),
    path('shop/store/shopnow/<str:pk>/',views.shopnowSetting,name="shopnow_setting"),
    path('shop/store/create/order/',views.createOrder,name="create_order"),
    path('shop/store/customer/<str:phone>/',views.fetchCustomer,name="fetch_customer"),
    path('shop/store/control/panel/',views.controlPanel,name="control_panel"),
    path('shop/store/customer/details/<str:pk>/',views.customerDetails,name="customer_details"),
]

furniture/noksha/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class ProductForm(ModelForm):
    name = forms.CharField(label='Product Name',widget=forms.TextInput(attrs={'placeholder': 'Product Name'}))
    price = forms.FloatField(label='Price',widget=forms.TextInput(attrs={'placeholder': 'Price'}))
    description = forms.CharField(max_length=2000,label='Description',widget=forms.Textarea(attrs={'placeholder': 'Description'}))
    product_code = forms.CharField(max_length=200,label='Product Code',widget=forms.TextInput(attrs={'placeholder': 'Product code'}))
    category = forms.ModelMultipleChoiceField(
            queryset=Category.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    color = forms.ModelMultipleChoiceField(
            queryset=Color.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    size = forms.ModelMultipleChoiceField(
            queryset=Size.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True)
    
    class Meta:
        model = Product
        fields = '__all__'

furniture/noksha/views.py
from django.contrib.auth.hashers import check_password
from django.urls import reverse
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from .models import *
from .utils import *
from .forms import *
from .decorators import *
import math
import json
import datetime

# Create your views here.
def logoutUser(request):
    logout(request)
    return redirect('noksha:home')

def loginUser(request):
    #Navbar Section
    navbarCategoryObject =  IndivitualCategory.objects.get(category_for = 'nvcategory')
    navbarCategorys = navbarCategoryObject.categorys.all()

    #CartItem Section
    cookieData = cookieCart(request)
    cartItems = cookieData['cartItems']
    cartTotal = cookieData['cartTotal']
    order = cookieData['order']
    items = cookieData['items']
    total_items = len(items)
    delivery_charge_object = Delivery_charge.objects.get(w_delivery= 'Dhaka')
    delivery_charge = delivery_charge_object.fee
    price_total = 0

    #Login Section
    if request.method =='POST' and 'login_username' in request.POST:
        login_username = request.POST.get('login_username')
        password = request.POST.get('login_password')

        try:
            user_1 = User.objects.get(username = login_username)
            username = user_1.username
        except:
            customer_1 = Customer.objects.get(phone = login_username)
            user_1 =  customer_1.user
            username = user_1.username

        user = authenticate(request,username=username, password=password)
        login(request,user)
        if user_1.groups.all()[0].name == 'admin':
            return redirect('noksha:shop_dashboard')
        if user is not None:
            customer = Customer.objects.get(phone = login_username)
            shipping = ShippingAddress.objects.get(customer = customer)
            db_order, created = Order.objects.get_or_create(customer=customer, complete=False)
            db_order.cupon_code = order['cupon_code']
            db_order.cupon_amount = order['cupon_amount']
            db_order.address = shipping.address
            db_order.city = shipping.city
            db_order.state = shipping.state
            db_order.save()
            for item in items:
                product = Product.objects.get(id=item['product']['id'])
                quantity = item['quantity']
                rate = product.price
                total = float(product.price) * float(quantity)
                orderItem, created  = OrderItem.objects.get_or_create(
                    product=product,
                    order = db_order,
                    customer=customer
                )
                orderItem.quantity=item['quantity']
                orderItem.size = item['size']
                orderItem.color = item['color']
                orderItem.rate = rate,
                orderItem.total = total
                orderItem.save()
            messages.success(request,'Login Successfull!')
            return redirect('noksha:home')
        else:
            messages.error(request,'Login failed. Please try again!')
            return redirect('noksha:login')
    if total_items > 0:
        for item in items:
            product = Product.objects.get(id = item['product']['id'])
            item['sizes'] = product.size.all()
            item['colors'] = product.color.all()
            item['image'] = ProductImages.objects.filter(product = product)[:1]
            price_total += product.price
    
        total = float(price_total) + float(delivery_charge)

        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,
            'order':order,
            'items':items,
            'item.image':item['image'],
            'item.sizes':item['sizes'],
            'item.colors':item['colors'],
            'delivery_charge':delivery_charge,
            'total':total,

        }
    else:
        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,

        }
    return render(request,'accounts/login.html',context)

def signUpUser(request):
    #Navbar Section
    navbarCategoryObject =  IndivitualCategory.objects.get(category_for = 'nvcategory')
    navbarCategorys = navbarCategoryObject.categorys.all()

    #CartItem Section
    cookieData = cookieCart(request)
    cartItems = cookieData['cartItems']
    cartTotal = cookieData['cartTotal']
    order = cookieData['order']
    items = cookieData['items']
    total_items = len(items)
    delivery_charge_object = Delivery_charge.objects.get(w_delivery= 'Dhaka')
    delivery_charge = delivery_charge_object.fee
    price_total = 0

    #SignUp Section
    if request.method =='POST' and 'reg_name' in request.POST:
        name =  request.POST.get('reg_name')
        email =  request.POST.get('reg_email')
        phone =  request.POST.get('reg_phone')
        password1 =  request.POST.get('reg_password1')
        password2 =  request.POST.get('reg_password2')
        address =  request.POST.get('address')
        area =  request.POST.get('area')
        city =  request.POST.get('city')
        if User.objects.filter(email=email).first():
            messages.error(request, 'Email is taken.')
            return redirect('noksha:sign_up')
        elif Customer.objects.filter(phone = phone).first():
            messages.error(request, 'Phone is used on another account.')
            return redirect('noksha:sign_up')
        elif password1 != password2:
            messages.error(request, "Password didn't match!.")
            return redirect('noksha:sign_up')
        else:
            user = User.objects.create(first_name = name, email=email,username=phone)
            user.set_password(password1)
            user.save()
            customer = Customer.objects.create(
                    user = user,
                    phone = phone,
            )
            shipping =  ShippingAddress.objects.create(
                customer = customer,
                address = address,
                state = area,
                city = city
            )
            group = Group.objects.get(name = 'customer')
            user.groups.add(group)
            if user is not None:
                db_order, created = Order.objects.get_or_create(customer=customer, complete=False)
                db_order.address = shipping.address
                db_order.city = shipping.city
                db_order.state = shipping.state
                db_order.save()
                for item in items:
                    product = Product.objects.get(id=item['product']['id'])
                    quantity = item['quantity']
                    rate = product.price
                    total = float(product.price) * float(quantity)
                    orderItem, created  = OrderItem.objects.get_or_create(
                       product=product,
                        order = db_order,
                        customer=customer, 
                        )
                    orderItem.quantity=item['quantity']
                    orderItem.size = item['size']
                    orderItem.color = item['color']
                    orderItem.rate = rate,
                    orderItem.total = total
                    orderItem.save()
                login(request,user)
            messages.success(request,'Login Successfull!')
        return redirect('noksha:home')
    
    if total_items > 0:
        for item in items:
            product = Product.objects.get(id = item['product']['id'])
            item['sizes'] = product.size.all()
            item['colors'] = product.color.all()
            item['image'] = ProductImages.objects.filter(product = product)[:1]
            price_total += product.price
    
        total = float(price_total) + float(delivery_charge)

        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,
            'order':order,
            'items':items,
            'item.image':item['image'],
            'item.sizes':item['sizes'],
            'item.colors':item['colors'],
            'delivery_charge':delivery_charge,
            'total':total,

        }
    else:
        context ={
            'cartItems':cartItems,
            'cartTotal':cartTotal,
            'nvCategorys':navbarCategorys,

        }
    return render(request,'accounts/registration.html',context)

@login_required(login_url='noksha:login')
def accountProfile(request,pk):
    user = request.user
    customer = request.user.customer
    user_orders = Order.objects.filter(customer=customer,complete = True).order_by('-date_created')

    #Status Section 
    total_orders = user_orders.count()
    delivered = user_orders.filter(status = 'Delivered').count()
    transit = user_orders.filter(status = 'In-Transit').count()
    confirmed = user_orders.filter(status = 'Admin Confirmed').count()
    pending = user_orders.filter(status = 'Customer Confirmed').count()
    
    status = {
        'total_orders':total_orders,
        'delivered':delivered,
        'transit':transit,
        'confirmed':confirmed, 
        'pending':pending,
    }

    #Wish List Section
    wish_products = []
    total_wish_products = 0
    if WishList.objects.filter(customer = customer).exists():
        wish_object = WishList.objects.get(customer = customer)
        for i in wish_object.products.all():

furniture/noksha/templates/store/pages/cart.html
{% extends 'store/main.html' %}
{% block content %}
<style>
    .header-fix{
        height: 100px;
    }
</style>
<div class="header-fix"></div>
{% if cartItems <= 0 %}
<div id="error-not-found" class="container">
    <h1>Shopping Cart</h1>
    <p>Your shopping cart is empty!</p>
    <div class="buttons clearfix">
        <div class="pull-right">
            <a href="{% url 'noksha:home' %}" class="btn btn-primary">Continue</a>
        </div>
    </div>
</div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <aside class="col-lg-9">
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right d-none d-md-block" width="200"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in items %}
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside">
                                            {% for i in item.image %}
                                    <img src="{{i.n_img.url}}" alt="{{item.product.name}}" class="img-sm" title="{{item.product.name}}" class="img-thumbnail">
                                    {% endfor %}</div>
                                        <figcaption class="info"> <a href="{% url 'noksha:product_view' item.product.id %}" class="title text-dark" data-abc="true">{{item.product.name}}</a>
                                            <p class="text-muted small">SIZE: {{item.size}} <br> COLOR: {{item.color}}</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td> <button type="button" style="float: left;" class="btn update-cart" data-product="{{item.product.id}}" data-action="remove"><i class="fa fa-minus" aria-hidden="true"></i></button>
                                    <p style="float: left; padding: 5px;">{{item.quantity}}</p>
                                    <button style="float: left;" type="button" data-product="{{item.product.id}}" data-action="add"  class="btn update-cart"><i class="fa fa-plus" aria-hidden="true"></i></button> </td>
                                <td>
                                    <div class="price-wrap"> <var class="price">{{item.get_total|floatformat:0}}&#2547;</var> <small class="text-muted"> {{item.product.price|floatformat:0}}&#2547; each </small> </div>
                                </td>
                                <td class="text-right d-none d-md-block"> <a class="btn btn-light update-cart" style="color: #fff;" data-abc="true" data-product="{{item.product.id}}" data-action="delete"> Remove</a> </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </aside>
        <aside class="col-lg-3">
            <div class="card mb-3">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group"> <label>Have coupon?</label>
                            <div class="input-group"> <input type="text" class="form-control coupon" name="coupon" placeholder="Coupon code"> <span class="input-group-append"> <button type="submit" class="btn btn-primary btn-apply coupon">Apply</button> </span> </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <dl class="dlist-align">
                        <dt>Total price:</dt>
                        <dd class="text-right ml-3">{{cartTotal|floatformat:0}}&#2547;</dd>
                    </dl>
                    <dl class="dlist-align">
                        <dt>Charges (Inside Dhaka):</dt>
                        <dd class="text-right text-dark ml-3">+ {{delivery_charge|floatformat:0}}&#2547;</dd>
                    </dl>
                    <dl class="dlist-align">
                        <dt>Discount:</dt>
                        <dd class="text-right text-danger ml-3">- {{order.cupon_amount|floatformat:0}}&#2547;</dd>
                    </dl>
                    <dl class="dlist-align">
                        <dt>Total:</dt>
                        <dd class="text-right text-dark b ml-3"><strong>{{total|floatformat:0}}&#2547;</strong></dd>
                    </dl>
                    <hr> <a href="{% url 'noksha:checkout' %}" class="btn btn-out btn-primary btn-square btn-main" data-abc="true"> Make Purchase </a> <a href="{% url 'noksha:home' %}" class="btn btn-out btn-success btn-square btn-main mt-2" data-abc="true">Continue Shopping</a>
                </div>
            </div>
        </aside>
    </div>
</div>
{% endif %}
{% endblock %}

furniture/noksha/templates/store/pages/categoryview.html
{% extends 'store/main.html' %}

{% block content %}
<style>
    .header-fix{
        height: 100px;
    }
    .all-categorys{
        max-height: 250px;
        overflow: auto;
    }
    .all-categorys ul{
        list-style: none;
        margin-left: 0px;
    }
    a{
        color: black;
    }
    hr {
        margin-top: 1rem;
        margin-bottom: 1rem;
        border: 0;
        border-top: 1px solid rgb(0 0 0);
    }
    .sub-categorys{
        display: flex;
        justify-content: space-evenly;
        margin-top: 50px;
    }
    .sub-categorys .col-sm-2{
        width: 150px;
    }
    .mvcontent{
        padding: 5px 25px;
        border: none;
        background-color: transparent;
        cursor: pointer;
    }
    .mvcontent:hover{
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        transition: 0.2s;
    }
</style>
<div class="header-fix"></div>
<div class="row" style="width: 100%;">
    <div class="col-sm-3 all-categorys">
        <h4 class="text-center"> Categories</h4>
        {% for i in all_categorys %}
        <ul>
            <li><a href="{% url 'noksha:category_view' i.category_id %}">{{i.category_name}}</a>
                {% if i.subcategorys %}
                <ul>
                    {% for j in i.subcategorys %}
                    <li><a href="{% url 'noksha:sub_category_view' j.id %}">{{j.name}}</a></li>
                    {% endfor %}
                </ul>
                {% endif %}
            </li>
        </ul>
        {% endfor %}
    </div>
    <div class="col-sm-9"> <hr>
        <div class="row sub-categorys">
            {% for i in subcategorys %}
            <div class="col-sm-2">
                <button class="mvcontent">
                    <a href="{% url 'noksha:sub_category_view' i.id %}">
                        <img src="{{i.img.url}}" alt="{{i.name}}"> <br>
                        <p>{{i.name}}</p>
                    </a>
                    
                </button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

furniture/noksha/templates/store/pages/home.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
<style>
    #home .banner-img{
        max-height: 649px;
    }
    #home .carousel-caption{
        bottom: 170px;
    }
    #popular-furniture .mvcontent{
        padding: 5px 25px;
        border: none;
        background-color: transparent;
        cursor: pointer;
    }
    #popular-furniture .mvcontent:hover{
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        transition: 0.2s;
    }
    #popular-furniture .category-content{
        max-height: 300px;
        overflow: auto;
    }
    #space-based-furniture .sbcontent a,
    #office-furniture-categories .ofcontent a,
    #interior-based-furniture .iecontent a{
        color: brown;
    }
    #space-based-furniture .sbcontent a:hover,
    #office-furniture-categories .ofcontent a:hover,
    #interior-based-furniture .iecontent a:hover{
        color: aqua;
        transition: 0.5s;
        text-decoration: none;
    }
    
    .category-content{
        display: flex;
        justify-content: space-evenly;
        margin-top: 50px;
    }
    .category-content .col-sm-2{
        width: 150px;
    }
</style>
<section id="home">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            {% for i in hbcimage %}
            <div class="{% cycle 'carousel-item active' 'carousel-item' 'carousel-item' %}">
                <a href="#"><img class="d-block w-100 banner-img" src="{{i.banner_img.url}}" alt="First slide"></a>
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="font-size: 35px;">{{i.title_heading}}</h5> <br>
                    <a href="{% url 'noksha:category_view' i.estimated_category.id %}" class="btn btn-danger">Explore Now</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
        </a>
    </div>
</section> <br><br>
<section id="popular-furniture">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="heading text-center">
                    <h3>Popular Furniture By Choice</h3>
                    <p>Categories our customers love to check out.</p>
                </div> <br>
            </div>
        </div>
        <div class="row category-content">
            {% for i in mvCategorys %}
            <div class="col-sm-2">
                <a href="{% url 'noksha:sub_category_view' i.id %}">
                    <button class="mvcontent">
                        <img src="{{i.img.url}}" alt="{{i.name}}"> <br>
                        <p>{{i.name}}</p>
                    </button>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section><br><br>
<section id="space-based-furniture">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="heading text-center">
                    <h3>Buy Furniture Based on Space</h3>
                    <p>Every Space has its unique needs.</p>
                </div> <br>
            </div>
        </div>
        <div class="row">
            {% for i in ccimage %}
            <div class="col-sm-4" style="margin-bottom: 20px;">
                <div class="sbcontent text-center">
                    <img width="100%" src="{{i.img.url}}"  alt="{{i.estimated_category.name}}"> <br> <br>
                    <p style="margin-bottom: 0px;">{{i.estimated_category.name}}</p>
                    <a href="{% url 'noksha:category_view' i.estimated_category.id %}">EXPLORE NOW ></a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section><br><br>
<section id="office-furniture-categories">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="heading text-center">
                    <h3>Office Furniture Categories</h3>
                    <p>All a contemporary office should have.</p>
                </div> <br>
            </div>
        </div>
        <div class="row">
            {% for i in sncimage %}
            <div class="col-sm-4" style="margin-bottom: 20px;">
                <div class="ofcontent text-center">
                    <img width="100%" src="{{i.img.url}}"  alt="{{i.estimated_category.name}}"> <br> <br>
                    <p style="margin-bottom: 0px;">{{i.estimated_category.name}}</p>
                    <a href="{% url 'noksha:category_view' i.estimated_category.id %}">EXPLORE NOW ></a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section><br><br>
<section id="interior-based-furniture">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="heading text-center">
                    <h3>Buy Furniture Based on Interior & Exterior</h3>
                    <p>Let's think smart and be the trendsetter.</p>
                </div> <br>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6" style="margin-bottom: 20px;">
                <div class="iecontent text-center">
                    <img width="100%" src="{% static 'images/photo-1618221195710-dd6b41faaea6.jpg' %}"> <br> <br>
                    <p style="margin-bottom: 0px;">Interior</p>
                    <a href="#">EXPLORE NOW ></a>
                </div>
            </div>
            <div class="col-sm-6" style="margin-bottom: 20px;">
                <div class="iecontent text-center">
                    <img width="100%" src="{% static 'images/download.jpg' %}"> <br> <br>
                    <p style="margin-bottom: 0px;">Exterior</p>
                    <a href="#">EXPLORE NOW ></a>
                </div>
            </div>
        </div>
    </div>
</section><br><br>
{% endblock %}

furniture/noksha/templates/store/pages/subcategoryview.html
{% extends 'store/main.html' %}
{% block content %}
<style>
    .header-fix{
        height: 100px;
    }
    @media only screen and (max-width: 600px) {
        .all-categorys{
            max-height: 250px;
            overflow: auto;
        }
    }
    .all-categorys ul{
        list-style: none;
        margin-left: 0px;
    }
    a{
        color: black;
    }
    hr {
        margin-top: 1rem;
        margin-bottom: 1rem;
        border: 0;
        border-top: 1px solid rgb(0 0 0);
    }
    .sub-categorys{
        display: flex;
        justify-content: space-evenly;
        margin-top: 50px;
    }
    .sub-categorys .col-sm-2{
        width: 150px;
    }
    .mvcontent{
        padding: 5px 25px;
        border: none;
        background-color: transparent;
        cursor: pointer;
    }
    .mvcontent:hover{
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        transition: 0.2s;
    }
</style>
<div class="header-fix"></div>
<div class="row" style="width: 100%;">
    <div class="col-sm-3 all-categorys">
        <h4 class="text-center"> Categories</h4>
        {% for i in all_categorys %}
        <ul>
            <li><a href="{% url 'noksha:category_view' i.category_id %}">{{i.category_name}}</a>
                {% if i.subcategorys %}
                <ul>
                    {% for j in i.subcategorys %}
                    <li><a href="{% url 'noksha:sub_category_view' j.id %}">{{j.name}}</a></li>
                    {% endfor %}
                </ul>
                {% endif %}
            </li>
        </ul>
        {% endfor %}
    </div>
    <div class="col-sm-9"> <hr>
        <div class="row sub-categorys">
            {% for i in products %}
            <div class="card" style="width: 18rem;">
                <img src="{{i.image_1}}" class="card-img-top" alt="..."><hr>
                <div class="card-body">
                  <h5 class="card-title">{{i.name}}</h5>
                  <p class="card-text">&#2547;{{i.price|floatformat:0}}</p>
                  <a href="{% url 'noksha:product_view' i.id %}" class="btn btn-outline-success">View Details</a>
                </div>
              </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}